#!/usr/bin/env zsh
# Generate completion file for a command
# Usage: zsh generate-completions.zsh <command-name>

set -e

if [[ -z "$1" ]]; then
    echo "Usage: $0 <command-name>"
    echo ""
    echo "Generates a completion file template for the specified command."
    echo ""
    echo "Example:"
    echo "  $0 myapp"
    echo ""
    exit 1
fi

cmd="$1"
output_dir="${2:-~/.zsh/completions}"
output_file="$output_dir/_$cmd"

mkdir -p "$output_dir"

# Check if command exists
if ! command -v "$cmd" &>/dev/null; then
    echo "Warning: Command '$cmd' not found in PATH"
    echo ""
fi

# Generate template
cat > "$output_file" << 'TEMPLATE'
#compdef COMMAND_NAME

# Completion for COMMAND_NAME
# Generated by generate-completions.zsh

_COMMAND_NAME() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '(-v --version)'{-v,--version}'[Show version]' \
        '(-q --quiet)'{-q,--quiet}'[Quiet output]' \
        '(-V --verbose)'{-V,--verbose}'[Verbose output]' \
        '1: :->cmds' \
        '*::arg:->args'

    case "$state" in
        cmds)
            _values "COMMAND_NAME command" \
                "help[Show help]" \
                "version[Show version]" \
                "init[Initialize something]" \
                "run[Run something]"
            ;;
        args)
            case $line[1] in
                init)
                    _arguments \
                        '--name[Project name]:name:' \
                        '--type[Project type]:type:(basic advanced)' \
                        '*:directory:_files -/'
                    ;;
                run)
                    _arguments \
                        '--config[Config file]:config:_files -g "*.{json,yaml,yml}"' \
                        '--output[Output directory]:output:_files -/' \
                        '*:input files:_files'
                    ;;
            esac
            ;;
    esac
}

_COMMAND_NAME "$@"
TEMPLATE

# Replace placeholder with actual command name
sed -i.bak "s/COMMAND_NAME/$cmd/g" "$output_file" 2>/dev/null || \
    sed -i '' "s/COMMAND_NAME/$cmd/g" "$output_file"
rm -f "${output_file}.bak"

echo "Generated completion file: $output_file"
echo ""
echo "To use it:"
echo "1. Ensure $output_dir is in your fpath (add to .zshrc):"
echo "   fpath=($output_dir \$fpath)"
echo ""
echo "2. Rebuild completions:"
echo "   rm -f ~/.zcompdump* && compinit"
echo ""
echo "3. Edit $output_file to match your command's options"
echo ""
echo "Completion reference:"
echo "- _arguments: Define flags and positional arguments"
echo "- _values: Define subcommands"
echo "- _files: Complete files (-/ for dirs, -g for glob)"
echo "- _describe: Simple list completion"
